import './globals.css';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });
const geistSans = Geist({ subsets: ['latin'], variable: '--font-geist-sans' });
const geistMono = Geist_Mono({ subsets: ['latin'], variable: '--font-geist-mono' });

export const metadata = {
  title: 'Stationery Store',
  description: 'Generated by create next app'
};

type RootProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootProps) {
  return (
    <html
      lang='vi'
      data-theme-preset='global'
      className={cn('h-full antialiased', geistSans.variable, geistMono.variable, 'font-sans', inter.variable)}
      suppressHydrationWarning
    >
      <body className='flex min-h-full flex-col'>
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
